CREATE SEQUENCE client_seq
    START WITH 4
    INCREMENT BY 1
    MINVALUE 1
    CACHE 10;
CREATE SEQUENCE author_seq
    START WITH 12
    INCREMENT BY 1
    MINVALUE 1
    CACHE 10;
CREATE SEQUENCE book_seq
    START WITH 12
    INCREMENT BY 1
    MINVALUE 1
    CACHE 10;
CREATE SEQUENCE bookcase_seq
    START WITH 4
    INCREMENT BY 1
    MINVALUE 1
    CACHE 10;
CREATE SEQUENCE shelf_seq
    START WITH 16
    INCREMENT BY 1
    MINVALUE 1
    CACHE 10;
CREATE SEQUENCE users_seq
    START WITH 4
    INCREMENT BY 1
    MINVALUE 1
    CACHE 10;